site_name: NeatText
site_url: https://example.com/
nav:
    - Home: index.md
    - User Guide: userguide.md
    - API Guide: apireference.md
    - Contributing: contributing.md
    - About: about.md

theme: readthedocs